extends SceneTree
const Life = preload("res://scripts/ship_life_state.gd")
var passed := 0
var failed := 0

func _init() -> void:
	call_deferred("run")

func check(condition: bool, label: String) -> void:
	if condition: passed += 1
	else:
		failed += 1
		printerr("SHIP LIFE FAIL: ", label)

func close(a: float, b: float) -> bool:
	return absf(a - b) < 0.00001

func ready_day(state) -> void:
	state.daily_food = 1.0
	state.daily_water = true
	state.hygiene = 80.0
	for sensor in state.selected_sensors: solve_sensor(state, sensor)

func solve_sensor(state, sensor: String) -> void:
	state.check_sensor(sensor)
	if state.calibration.is_empty(): return
	for i in 3:
		state.trim_sensor(["a", "b", "c"][i], int(state.calibration.target[i])-int(state.calibration.readings[i]))
	state.submit_sensor()

func calibration_checks() -> void:
	var state = Life.new()
	var due: String = state.selected_sensors[0]
	check(not state.sensor_text().contains("CHECK DUE"), "engineering status never reveals daily assignments")
	var unrelated: String = ""
	for sensor in Life.SENSOR_NAMES:
		if sensor not in state.selected_sensors: unrelated=sensor;break
	check(state.check_sensor(unrelated).contains("CALIBRATION /"), "unassigned sensors offer same puzzle without leaking schedule")
	check(state.checked_sensors.is_empty(), "starting a check grants no inspection credit")
	var before: Dictionary=state.snapshot()
	check(state.check_sensor(due).contains("Finish or cancel"), "changing sensor cannot silently discard active puzzle")
	state.trim_sensor("bad", 2);state.trim_sensor("a", 100)
	check(state.snapshot()==before, "invalid trim leaves puzzle and condition unchanged")
	state.cancel_calibration()
	check(state.degraded_sensors.is_empty(), "cancelling an unsubmitted test has no penalty")
	state.check_sensor(due)
	check(state.submit_sensor().begins_with("DEGRADED") and due in state.degraded_sensors and due not in state.checked_sensors, "wrong calibration fails and records degraded without completing daily check")
	var condition: float=state.sensors[due]
	check(condition==100, "failed calibration does not invent instant structural damage")
	state.check_sensor(due)
	var first: Dictionary=state.calibration.duplicate(true)
	state.trim_sensor("a",int(first.target[0])-int(first.readings[0]))
	var saved: Dictionary=state.snapshot()
	var loaded=Life.new();loaded.restore(JSON.parse_string(JSON.stringify(saved)))
	check(loaded.snapshot()==state.snapshot(), "in-progress trim and degraded result survive JSON save")
	solve_sensor(loaded,due)
	check(due in loaded.checked_sensors and due not in loaded.degraded_sensors, "correct readings pass and clear calibration fault")
	check(loaded.sensors[due]==condition, "passing calibration cannot repair lost condition")
	loaded.sensors[due]=77.0
	check(loaded.check_sensor(due).contains("already checked") and loaded.sensors[due]==77.0, "repeat checks cannot farm condition or wear credit")
	state.advance(18.0)
	check(state.calibration.is_empty() and is_equal_approx(state.sensors[due],98.5), "midnight cancels old puzzle and applies degraded wear once")
	check(due in state.degraded_sensors, "degraded calibration survives day rollover until corrected")
	state.repair(due)
	check(due not in state.degraded_sensors and state.sensors[due]==100, "paid port service clears degraded status")
	state.restore({"calibration":{"sensor":due,"day":1,"target":[1,2,3],"readings":[0,999,2]}})
	check(state.calibration.is_empty(), "corrupt out-of-range puzzle save is rejected safely")

func run() -> void:
	calibration_checks()
	var clock=Life.new()
	clock.advance(4.999/60.0)
	check(clock.time_text()=="DAY 01 / 06:00 AST", "clock display rounds down rather than counting every minute")
	clock.advance(0.001/60.0)
	check(clock.time_text()=="DAY 01 / 06:05 AST", "clock reaches the next five-minute display boundary")
	clock.elapsed_hours=23.999
	check(clock.time_text()=="DAY 01 / 23:55 AST", "rounded clock never advertises tomorrow before midnight")
	clock.advance(0.001)
	check(clock.time_text()=="DAY 02 / 00:00 AST", "calendar rollover retains correct day with rounded clock")
	clock=Life.new();clock.advance(3600.0*Life.WORLD_HOURS_PER_SECOND)
	check(clock.day()==2 and is_equal_approx(clock.hour(),6.0), "one real hour is exactly one game day")
	var life = Life.new()
	check(life.day() == 1 and close(life.hour(), 6.0), "initial calendar is day1 at06")
	check(life.time_text() == "DAY 01 / 06:00 AST", "calendar formats stable shared clock")
	check(life.food_stock == 0 and life.water_stock == 0 and life.capacity == 12, "empty twelve-day pantry")
	check(life.sensors.size() == 6 and life.selected_sensors.size() == 2, "all sensors and two daily checks")
	check(life.selected_sensors == Life.new().selected_sensors, "daily selections are reproducible")
	check(life.selected_sensors[0] != life.selected_sensors[1], "checks do not duplicate a sensor")
	check(life.can_depart(), "healthy sensors permit departure")
	check(not life.checklist_complete(), "initial chores pending")
	check(life.purchase_error("food", -1) != "" and life.purchase_error("water", 13) != "", "invalid quantities rejected")
	life.purchase("food", 0)
	check(life.food_stock == 0, "zero units has no minimum and causes no purchase")
	life.purchase("food", 12)
	life.purchase("water", 12)
	check(life.food_stock == 12 and life.water_stock == 12, "independent full capacity")
	life.purchase("food", 1)
	check(life.food_stock == 12 and not life.last_error.is_empty(), "overflow cannot charge or store extra")
	life.interact("fridge")
	check(life.hand_item == "raw_food" and life.food_stock == 11, "fridge reserves food exactly once")
	life.interact("fridge")
	check(life.food_stock == 11, "occupied hand cannot duplicate food")
	life.interact("cabinet")
	check(life.hand_item == "raw_food", "only one carried living item")
	life.interact("sink")
	check(life.hand_item == "raw_food", "sink cannot erase edible provisions")
	life.interact("oven")
	check(life.hand_item == "" and life.oven_state == "cooking", "oven takes packet and starts timer")
	life.interact("oven")
	check(life.hand_item == "", "cannot take uncooked meal")
	life.tick_interactions(2.0)
	check(life.oven_state == "cooking" and close(life.cook_remaining, 2.0), "cooking progresses in real seconds")
	life.tick_interactions(2.0)
	life.interact("oven")
	check(life.hand_item == "meal" and life.hand_bites == 5 and life.oven_state == "", "cooking yields exactly one five-bite plate")
	life.interact("table")
	check(life.table_bites == 5 and life.hand_item == "", "plate placed before eating")
	life.interact("table")
	check(life.table_bites == 4 and close(life.daily_food, 0.2), "first bite restores one fifth")
	life.interact("take_plate")
	check(life.hand_item == "meal" and life.hand_bites == 4 and life.table_bites == -1, "partial meal can be moved without loss")
	life.interact("table")
	check(life.table_bites == 4, "partial portion not refilled when replaced")
	for bite in 4: life.interact("table")
	check(life.table_bites == 0 and close(life.daily_food, 1.0), "five bites complete day and leave dirty plate")
	check(life.food_stock == 11, "cooking eating moving consume only one food unit")
	# A newly cooked plate cannot replace the dirty plate; clearing is required.
	life.hand_item = "meal"
	life.hand_bites = 5
	life.interact("table")
	check(life.hand_item == "meal" and life.table_bites == 0, "uncleared plate blocks next meal")
	life.hand_item = ""
	life.hand_bites = 0
	life.interact("table")
	check(life.hand_item == "dirty_plate" and life.table_bites == -1, "dirty plate picked up after eating")
	life.interact("sink")
	check(life.hand_item == "" and life.table_bites == -1, "sink clears used plate")
	life.interact("fridge")
	check(life.hand_item == "" and life.food_stock == 11, "satisfied daily food does not waste additional stock")
	life.interact("cabinet")
	life.interact("cooler")
	check(life.hand_item == "water_glass" and life.water_stock == 11 and not life.daily_water, "filling reserves water before drinking")
	life.interact("cooler")
	check(life.water_stock == 11, "refilling full glass cannot consume twice")
	life.interact("sink")
	check(life.hand_item == "water_glass", "filled water cannot be lost through sink")
	life.interact("drink")
	check(life.daily_water and life.hand_item == "used_glass", "drinking satisfies daily water and leaves used glass")
	life.interact("drink")
	check(life.water_stock == 11, "repeated drink cannot duplicate stock effects")
	life.interact("cooler")
	check(life.hand_item == "used_glass" and life.water_stock == 11, "used glass must be washed")
	life.interact("sink")
	check(life.hand_item == "", "sink washes and returns glass")
	life.hygiene = 20.0
	life.tick_interactions(4.0, true)
	check(close(life.hygiene, 40.0) and life.water_stock == 11, "shower restores hygiene with recycled utility water")
	life.tick_interactions(30.0, true)
	check(life.hygiene == 100.0, "shower hygiene capped")
	check(life.survival_ready() and not life.checklist_complete(), "survival ready independent of pending sensor checks")
	life.print_checklist()
	life.print_checklist()
	check(life.printed_day == 1 and life.daily_food == 1.0, "printing never creates or resets daily tasks")
	for sensor in life.selected_sensors: solve_sensor(life, sensor)
	check(life.checklist_complete(), "existing completed actions count before print")
	var selected: Array = life.selected_sensors.duplicate()
	life.check_sensor(selected[0])
	check(life.checked_sensors.size() == 2, "repeated checks cannot stack wear bonuses")
	check(life.check_sensor("unknown").begins_with("Unknown"), "invalid sensor rejected")
	check(not life.rest_plan("sleep").ok, "sleep blocked at06 despite complete checklist")
	var plan: Dictionary = life.start_rest("pass")
	check(plan.ok and close(plan.hours, 14.0), "completed day can pass from06 to20")
	check(close(life.hour(), 6.0), "rest planning does not advance before progress UI")
	life.advance(plan.hours)
	check(close(life.hour(), 20.0) and life.day() == 1, "pass ends at bedtime")
	check(not life.rest_plan("pass").ok, "cannot repeatedly pass beyond bedtime")
	plan = life.start_rest("sleep")
	check(plan.ok and close(plan.hours, 10.0), "20:00 sleep targets next06")
	life.advance(plan.hours)
	check(life.day() == 2 and close(life.hour(), 6.0), "normal sleep crosses exactly one calendar boundary")
	check(life.daily_food == 0.0 and not life.daily_water and life.checked_sensors.is_empty(), "new calendar day resets daily requirements once")
	check(close(life.sensors[selected[0]], 99.5) and close(life.sensors[selected[1]], 99.5), "checked selected sensors wear at half rate")
	for sensor in Life.SENSOR_NAMES:
		if sensor not in selected: check(close(life.sensors[sensor], 99.0), "unselected sensor wears at normal rate " + sensor)
	var condition := float(life.sensors[selected[0]])
	life.advance(0.0)
	life.advance(-1.0)
	life.advance(NAN)
	check(close(life.sensors[selected[0]], condition), "invalid advances do not duplicate day wear")
	var missed: String = life.selected_sensors[0]
	var missed_before := float(life.sensors[missed])
	life.advance(18.0)
	check(life.day() == 3 and close(life.hour(), 0.0), "exact midnight advances day")
	check(close(life.sensors[missed], missed_before - 1.5), "unchecked selected sensor wears at1.5rate")
	var after_midnight := float(life.sensors[missed])
	life.advance(0.0001)
	check(close(life.sensors[missed], after_midnight), "boundary cannot be charged twice")
	life.sensors.navigation = 0.0
	check(not life.can_depart(), "failed sensor blocks takeoff")
	check(life.repair_quote("navigation") == 200, "repair quote prices missing condition")
	life.check_sensor("navigation")
	check(life.sensors.navigation == 0.0, "checks cannot repair failed sensors")
	life.repair("navigation")
	check(life.can_depart() and life.sensors.navigation == 100.0, "port repair restores departure")
	check(life.repair_quote("nonsense") == -1, "invalid repairs cannot be charged")
	life.repair("all")
	check(life.repair_quote() == 0, "repairall restores all sensors")
	var emergency = Life.new()
	check(emergency.rest_plan("emergency").ok, "empty pantry permits emergency rest")
	for count in 3:
		var emergency_plan: Dictionary = emergency.start_rest("emergency")
		check(emergency_plan.ok and emergency.emergency_uses == count + 1, "emergency use debited exactly once " + str(count))
		emergency.advance(emergency_plan.hours)
		check(close(emergency.hour(), 6.0), "emergency rest also wakes at06 " + str(count))
	check(not emergency.game_over and emergency.rest_plan("emergency").get("fatal", false), "three rests allowed and fourth warning shown")
	check(not emergency.game_over, "previewing fourth rest never ends run")
	var terminal_plan: Dictionary = emergency.start_rest("emergency")
	check(not terminal_plan.ok and emergency.game_over, "fourth committed emergency ends run")
	var ended_time := float(emergency.elapsed_hours)
	emergency.advance(24.0)
	check(emergency.elapsed_hours == ended_time, "ended run clock stops")
	var refill = Life.new()
	refill.emergency_uses = 3
	refill.begin_station_visit()
	check(refill.emergency_uses == 3, "docking does not reset emergency rests")
	refill.purchase("food", 1)
	check(refill.emergency_uses == 3, "food purchase alone not enough")
	refill.purchase("water", 0)
	check(refill.emergency_uses == 3, "zero water transaction not a resupply")
	refill.purchase("water", 1)
	check(refill.emergency_uses == 0, "separate actual food and water purchases samevisit reset allowance")
	refill.emergency_uses = 2
	refill.purchase("food", 1)
	check(refill.emergency_uses == 2, "previous qualifying pair cannot be reused")
	refill.begin_station_visit()
	refill.purchase("water", 1)
	check(refill.emergency_uses == 2, "purchases across different visits cannot combine")
	check(not refill.rest_plan("emergency").ok, "stocked provisions must be used before emergency rest")
	refill.daily_food = 1.0
	refill.daily_water = true
	check(not refill.rest_plan("emergency").ok, "satisfied player cannot spend emergency rests")
	var partial = Life.new()
	partial.purchase("food", 2)
	partial.purchase("water", 2)
	partial.interact("fridge")
	partial.interact("oven")
	partial.tick_interactions(1.25)
	partial.interact("cabinet")
	partial.interact("cooler")
	partial.check_sensor(partial.selected_sensors[0])
	partial.advance(2.3)
	partial.print_checklist()
	var saved: Dictionary = partial.snapshot()
	var restored = Life.new()
	restored.restore(JSON.parse_string(JSON.stringify(saved)))
	check(restored.snapshot() == partial.snapshot(), "JSON roundtrip preserves clock items cooking inventory checklist and sensors")
	restored.tick_interactions(2.75)
	check(restored.oven_state == "ready" and restored.hand_item == "water_glass", "restored cooking finishes while held glass retained")
	saved.sensors.navigation = 0.0
	check(partial.sensors.navigation > 0.0, "snapshot deeply copies authoritative sensor data")
	restored.restore({"elapsed_hours":-12.0, "food_stock":99, "water_stock":-5, "hygiene":INF, "hand_item":"fake", "sensors":{"navigation":-5}, "checked_sensors":["fake"], "emergency_uses":100})
	check(restored.elapsed_hours == 0.0 and restored.food_stock == 12 and restored.water_stock == 0, "restore clamps invalid calendar and inventory")
	check(restored.hygiene == 55.0 and restored.hand_item == "" and restored.checked_sensors.is_empty(), "restore sanitizes invalid state")
	check(restored.sensors.navigation == 0.0 and restored.sensors.coolant == 100.0 and restored.emergency_uses == 3, "restore defaults absent sensors and bounds emergency allowance")
	var one_step = Life.new()
	var small_steps = Life.new()
	ready_day(one_step)
	ready_day(small_steps)
	one_step.advance(60.0)
	for step in 240: small_steps.advance(0.25)
	check(one_step.snapshot() == small_steps.snapshot(), "skip and normal quarter-hour clock updates produce identical survival state")
	var early = Life.new()
	ready_day(early)
	early.advance(14.0)
	var day_checks: Array = early.selected_sensors.duplicate()
	early.advance(1.0) # A route arrival interrupts well before normal wake time.
	check(early.day() == 1 and early.selected_sensors == day_checks and early.checklist_complete(), "early wakeup within day does not create new tasks")
	check(early.rest_plan("sleep").ok and close(early.rest_plan("sleep").hours, 9.0), "sleep resumed after interruption still targets06")
	print("SHIP LIFE STATE: %d passed / %d failed" % [passed, failed])
	quit(1 if failed else 0)
